# Generated by Django 5.1.4 on 2024-12-23 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_pacientes', models.AutoField(primary_key=True, serialize=False)),
                ('apellido_paterno_pacientes', models.CharField(max_length=255)),
                ('apellido_materno_pacientes', models.CharField(max_length=255)),
                ('nombres_pacientes', models.CharField(max_length=255)),
                ('cedula_pacientes', models.CharField(max_length=15, unique=True)),
                ('fecha_nacimiento_pacientes', models.DateField()),
                ('direccion_pacientes', models.TextField()),
                ('email_pacientes', models.EmailField(max_length=254)),
                ('genero_pacientes', models.CharField(max_length=255)),
                ('telefono_pacientes', models.CharField(max_length=15)),
                ('emergencia_informar_pacientes', models.CharField(max_length=255)),
                ('contacto_emergencia_pacientes', models.CharField(max_length=15)),
                ('seguro_pacientes', models.CharField(max_length=255)),
                ('fk_id_admisionista', models.ForeignKey(blank=True, db_column='fk_id_admisionista', limit_choices_to={'tipo_usuario': 'admisionista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admisionista')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
