# Generated by Django 5.1.4 on 2025-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='estado_civil_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
