# Generated by Django 5.1.4 on 2025-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0002_pacientes_estado_civil_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='empresa_trabaja_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='grupo_cultura_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='instruccion_academica_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='lugar_nacimiento_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nacionalidad_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ocupacion_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='parentesco_pacientes',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
