# Generated by Django 5.1.4 on 2025-01-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0003_pacientes_empresa_trabaja_pacientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='grupo_cultura_pacientes',
            new_name='grupo_cultural_pacientes',
        ),
    ]
