# Generated by Django 5.0.6 on 2025-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0004_rename_grupo_cultura_pacientes_pacientes_grupo_cultural_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
