# Generated by Django 5.1.4 on 2025-01-21 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0005_pacientes_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('estado_cita', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADA', 'CONFIRMADA'), ('CANCELADA', 'CANCELADA'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=20)),
                ('fk_id_paciente', models.ForeignKey(db_column='fk_id_pacientes', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='admisionistas.pacientes')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_cita', '-hora_cita'],
            },
        ),
    ]
