# Generated by Django 5.1.4 on 2025-02-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisionistas', '0006_citas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
