# Generated by Django 5.1.4 on 2024-12-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_options_alter_usuarios_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('admisionista', 'Admisionista'), ('doctor', 'Doctor')], default='admisionista', max_length=20),
        ),
    ]
