# Generated by Django 5.0.6 on 2024-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('admisionista', 'Admisionista'), ('doctor', 'Doctor'), ('administrador', 'Administrador')], default='admisionista', max_length=20),
        ),
    ]
