# Generated by Django 5.0.6 on 2025-01-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('medico_general', 'Médico General'), ('admisionista', 'Admisionista'), ('administrador', 'Administrador')], max_length=50, null=True, verbose_name='Especialidad'),
        ),
    ]
