# Generated by Django 5.0.6 on 2025-01-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuarios_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
