# Generated by Django 5.0.6 on 2025-01-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisionistas', '0006_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion_historial', models.DateField()),
                ('hora_atencion_historial', models.TimeField()),
                ('presion_arterial_historial', models.CharField(max_length=50)),
                ('temperatura_historial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturacion_oxigeno_historial', models.IntegerField()),
                ('frecuencia_respiratoria_historial', models.IntegerField()),
                ('peso_historial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_historial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_sintoma_historial', models.TextField()),
                ('descripcion_sintoma_historial', models.TextField()),
                ('gravedad_sintoma_historial', models.CharField(max_length=255)),
                ('inicio_sintoma_historial', models.TextField()),
                ('duracion_sintoma_historial', models.TextField()),
                ('frecuecia_sintoma_historial', models.TextField()),
                ('tipo_sintoma_historial', models.TextField()),
                ('nombre_diagnostico_historial', models.TextField()),
                ('descripcion_diagnostico_historial', models.TextField()),
                ('cie10_diagnostico_historial', models.CharField(max_length=50)),
                ('medicamento_tratamiento_historial', models.TextField()),
                ('instrucciones_tratamiento_historial', models.TextField()),
                ('fecha_inicio_tratamiento_historial', models.DateField()),
                ('fecha_fin_tratamiento_historial', models.DateField()),
                ('observaciones_tratamiento_historial', models.TextField()),
                ('fk_id_cita', models.ForeignKey(db_column='fk_id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='admisionistas.citas')),
            ],
            options={
                'db_table': 'historial_clinico',
            },
        ),
    ]
