# Generated by Django 5.0.6 on 2025-01-23 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='fk_id_doctor',
            field=models.ForeignKey(blank=True, db_column='fk_id_admisionista', limit_choices_to={'tipo_usuario': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
    ]
